### ISSUE TITLE
[1.19.2] Issues

### ISSUE THREAD

**Issue by itsdinkd** [skycatminepokie/WBShop-Mod#42]
Econ doesnt work 

![image](https://user-images.githubusercontent.com/35115304/215283032-f048e04a-e51d-4637-8397-ac906ec8e154.png)

---

I setup a offer for a modded item giving 250 points, for 1 item. 

I donated the item via /donate

(mind you I already gave myself 25000 points to extend border for default border)

![image](https://user-images.githubusercontent.com/35115304/215283454-dba97802-1e8a-457e-aef2-56cc80999a4f.png)

I ended up losing points after donating? Also, can you add in a feature that tells the player what happened after they donated? without notice it seems I just lost the item. i would suggest saying `"Donate successful! {PointAmount} points given, extending border by X!"`

**Comment by skycatminepokie** [comment]
Thanks for letting me know about this! I didn't really document it well, did I?
First off, it should say /wbshop econ (or maybe /wbsmp econ, I haven't worked on this mod for a while now).
Second, /offer locks up your points to buy items from other players. I'm working on another project now, but I can probably hardcode some point values soon if you'd like.
